### ISSUE TITLE
Can be used in Browser or only on server with nodejs ?

### ISSUE THREAD

**Issue by joe-getcouragenow** [genjidb/genji.js#1]
Just wondering..

**Comment by asdine** [comment]
The end goal is to be able to use it on both platforms but my first goal is to be able to use it on the browser with wasm.
For NodeJS I don't know yet if we'll create a separate `node-genji` repository or store the code in this one. The main difference between the Node version and the wasm one would be mainly that the former would use a shared C library and the latter will use the wasm version.

**Comment by joe-getcouragenow** [comment]
Ok thanks for the response.

My goal is also to be able to use it in a browser as WASM.

I could not easily compile it using the standard golang wasm compiler.
Any chance you can update the readme for us mortals ?

Regarding gotiny, I did notice that the comments you left in the code pointing to Issues with gotiny have been fixed. At least the first 2 Issues i saw in your code.

This golang project has managed to get tinygo to work for it.
https://github.com/vugu-examples/tinygo
It worked for me. Here is my makefile: https://codeberg.org/gerard.webb/junk/src/branch/master/sdk/gui/vugo

**Comment by asdine** [comment]
The latest release of Tinygo doesn't yet contain all of the fixes and most importantly it contains some other bugs that need to be addressed (https://github.com/tinygo-org/tinygo/issues/1206)

Concerning `genji.js`, I still need to write an indexeddb engine, because the current engine stores all the data in memory, which is not ideal.

I will push a fix for the current version this weekend though, so that you can test it if you're interested 👍

**Comment by joe-getcouragenow** [comment]
Yep i am def interested in trying to get things working in the Browser . Thanks.

Btw, this is an excellent example of how useful Genji is: https://github.com/google/note-maps/blob/main/notes/genji/genji.go#L24
